### ISSUE TITLE
datetime AM PM not recognized

### ISSUE THREAD

**Issue by djhocking** [Conte-Ecology/conteStreamTemperature_web#15]
In some time series where the logger records the datetime with AM and PM rather than military time, the database seems to cut the AM/PM. This results in duplicates every hour or every half hour on a given day for a particular series ID. One example is `location_name = Finney`. If you plot that time series (before averaging to date) it looks funny because it inadvertently creates two measurements at each time (01:00 - 12:00) then skips the next half day.

When exporting Hobo Logger data the default is as an excel file with 12-hour time. These can be changed to csv and 24-hour time, but not everyone will do that (and may not have done that with old data). The excel to csv isn't a big issue but we need to be able to check the 12-hour vs. 24-hour as it goes into the database rather than when it comes out because that info is already lost.

Also, date and time can be in separate columns. I'm not sure how we handle that.

**Comment by djhocking** [comment]
Sorry looking at the website with Paul Damkot, it looks like this is already taken care of on the upload side. However, when I look at the data in R the AM/PM seems to be lost. I'm not sure if it's lost going into the database or coming out into R.

**Comment by walkerjeffd** [comment]
It's most likely a problem with the datetime format specified in the upload form. If the original file has AM/PM then the user must specify that in the datetime format field. Unfortunately this is not intuitive, and I haven't tested any files to see if the upload form can guess this correctly or not. 

When the file is uploaded, the datetimes are parsed from strings to date objects, which are then stored in the database. So the database actually just stores the datetime as the number of seconds since 1/1/1970 (UNIX timestamp), rather than the datetime string.  

I'll take a look at the Finney site and files to see what happened.

**Comment by djhocking** [comment]
Okay, I had Paul reupload some of the series for that location and it looks like it works fine. Sorry for the confusion. It must have occurred when he originally uploaded the data. He must have not used the guess and just let it default to date `HH:MM:ss` rather than `HH:MM:ss a`. It did guess correctly this time when I had time do it.

I'll have him replace the rest of the data for that location (2013 series).

**Comment by walkerjeffd** [comment]
Ok, glad it works, here's what I was about to send:

So there are three files for Finney Brook.

filename | datetime format | first timestamp
----------- | --------------------- | ---------------
Finney_Brook_A_....csv | M/D/YY HH:mm | 08/16/13 07:30:00 PM
Finney_Brook_B_....csv | MM/DD/YY hh:mm:ss a | 12/14/13 04:00:00 PM
Finney_Brook_C_....csv | MM/DD/YY H:mm:ss | 05/11/14 16:30:00

So the first one has an incorrect datetime format, it should be `M/D/YY HH:mm A` with the `A` at the end to specify `AM/PM`.

The second one might have worked right, but the lower case `a` specifies `am/pm` not `AM/PM`. 

Looks like the lower/upper case a or A doesn't actually matter if it worked.

**Comment by djhocking** [comment]
Originally they were all like the first one. I had him reupload the other two files, 1 in 24-hour format and 1 in 12-hour format and use the guess. They both worked. Strange that the capitalization didn't make a difference, but glad it worked.

**Comment by djhocking** [comment]
This wasn't caught originally because the plot on the website doesn't show that detail (plots the daily means?). Would it be worthwhile to plot all the original data or have that option?

**Comment by walkerjeffd** [comment]
we had that originally, but some timeseries have 20,000 data points or more, which is too much for d3 to handle. i was thinking about making it a zoomable time series plot, so when you zoom in to say a 7-day window it would show you the raw data, but haven't gotten that far yet.

it would be useful to come with a set of qaqc checks including this like this (e.g. within a given day, values are (approximately) distributed throughout the day). If we could create little functions that can test one time series at a time, then we can run a batch QAQC on all time series and at least get a list of the series that fail one or more checks.

**Comment by djhocking** [comment]
Those both sound like good plans
